spring.application.name=ReceptNeked

spring.datasource.url=jdbc:postgresql://dpg-d7u9lt9j2pic739mdedg-a.frankfurt-postgres.render.com:5432/recipes_8ncf
spring.datasource.username=prusko
spring.datasource.password=ShhSUiMzUNGo1Pl7Z3xJJWCM73g8rt2J
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update